golang-1.25-linux/1e4dadb8a796a20044e177a108eec65780cd59c308da84f7fdbfdbc758cdf312:
  size: 59768009
  object_id: 5dc9d54f-777b-45e1-48be-d1ff7bf358cc
  sha: sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: 528ab3a2-a20e-4cdd-47e1-59e8bf9e9688
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-linux/288cfe8883218087eeb75040802f471670df0e64e5c4d360b68b0109830b9329:
  size: 59766394
  object_id: 94331438-b14f-4bbd-5cf5-9f1e2b187124
  sha: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
golang-1.25-windows/976ff3d53aec4af1244ca8b2ab0be7ffd977dafd6dd805771df8508cb4998087:
  size: 67442664
  object_id: 515a08be-652e-41cb-585e-266417ee3f76
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
golang-1.25-windows/d59b40b0d4a5b7f3359d943bcd143637163db0351db4038ba7a1a490a0a6fbec:
  size: 67437540
  object_id: 2f3fefeb-125e-4a26-7126-061b67596693
  sha: sha256:c18b46f6aa44dbfcd54a9db19dd2fcc5ad684819addcfcf968aa75dad89a89c8
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: bd6b071b-f83f-4d1c-7e77-a23f52356561
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
