golang-1.25-linux/1e4dadb8a796a20044e177a108eec65780cd59c308da84f7fdbfdbc758cdf312:
  size: 59768749
  object_id: bab39b72-7cc5-4669-6f78-1be35b015d5e
  sha: sha256:12e6d6a191091ae27dc31f6efc630e3a3b8ba409baf3573d955b196fdf086005
golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: 528ab3a2-a20e-4cdd-47e1-59e8bf9e9688
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-linux/288cfe8883218087eeb75040802f471670df0e64e5c4d360b68b0109830b9329:
  size: 59766394
  object_id: 94331438-b14f-4bbd-5cf5-9f1e2b187124
  sha: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
golang-1.25-windows/117efdd98cac4d6d362504cddfb6e0926852569d5dd7330479e26c5477b5ada0:
  size: 67448678
  object_id: 7f7890ca-e009-4dfc-793e-e9742360163f
  sha: sha256:c75e5f4ff62d085cc0017be3ad19d5536f46825fa05db06ec468941f847e3228
golang-1.25-windows/976ff3d53aec4af1244ca8b2ab0be7ffd977dafd6dd805771df8508cb4998087:
  size: 67442664
  object_id: 096e0654-da68-407c-46db-16af2d41a2b5
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
golang-1.25-windows/924223df4c326000999e7554ab10919d80de3df3483a2eb60d0494771a9e073c:
  size: 67446385
  object_id: a957e07c-3538-4079-6c99-3cd0172e3027
  sha: sha256:19b4733b727ba5c611b5656187f3ac367d278d64c3d4199a845e39c0fdac5335
golang-1.25-windows/d59b40b0d4a5b7f3359d943bcd143637163db0351db4038ba7a1a490a0a6fbec:
  size: 67437540
  object_id: 2f3fefeb-125e-4a26-7126-061b67596693
  sha: sha256:c18b46f6aa44dbfcd54a9db19dd2fcc5ad684819addcfcf968aa75dad89a89c8
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: bd6b071b-f83f-4d1c-7e77-a23f52356561
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
